### ISSUE TITLE
Can't handler arrow function

### ISSUE THREAD

**Issue by erguotou520** [vuejs/vue-template-es2015-compiler#5]
After `vue@2.0.6`, I must remove the code like `@change="xxxx=arguments[0]"`, while I changed to `@change="(...args)=>{xxxx=args[0]}"` but get error saying `can't handler this type, need specify loader`.
So I want to know this `es2015 compiler` can't handler the arrow function?

**Comment by yyx990803** [comment]
fixed in 1.2.4

**Comment by erguotou520** [comment]
Still not support arrow function.
Code like 
```html
@selection-change="()=>{}"
```
will rendered like
```js
"selection-change": function($event) {
  () => {}
}
```
but not as function

**Comment by yyx990803** [comment]
arrow function is still not supported, the fix only allows old usage of `arguments`.

**Comment by erguotou520** [comment]
Does this in plan or not?

**Comment by yyx990803** [comment]
Yes.

**Comment by erguotou520** [comment]
Ok, thanks a lot.

**Comment by safarishi** [comment]
I met with a similar question?

I use component like below

```
<state-input
   type="text"
   class="input_type pay_width03"
   placeholder="0"
   @input-value-changed="(value) => onPercentageChanged({ index, value })"
 />

In the state-input of corresponding component I emit the event
this.$emit('input-value-changed', value)
```

Then what puzzled me is?

the syntax of `@input-value-changed="(value) => onPercentageChanged({ index, value })"`
is support now and will this have compatibility problem?
